### ISSUE TITLE
2nd it500 

### ISSUE THREAD

**Issue by cpass-watch** [floringhimie/salusfy#10]
Hi, this is not exactly an issue as I have the integration working great thank you. Is there a way to add a second thermostat with a different ID?

**Comment by Claudio1L** [comment]
I solved running a second container with a separated HA instance only to run "single tenant" integrations like this one. Then using https://github.com/custom-components/remote_homeassistant  I export the entities to the main instance.

**Comment by floringhimie** [comment]
Or you can simply duplicate the folder salusfy, rename it to salusfx and using notepad++ find&replace in files salusfy to salusfx and then in config use salusfx: etc you got the idea.

**Comment by floringhimie** [comment]
Please try to use the integration twice maybe works.
climate:
  - platform: salusfy
    username: "email@test.com"
    password: "pass"
    id: "1234567"
  - platform: salusfy
    username: "email@test.com"
    password: "pass"
    id: "7654321"

**Comment by Claudio1L** [comment]
No way, unique_id config is not supported

**Comment by floringhimie** [comment]
OK then... another way is to copy to your local PC from custom_components salusfy folder, rename the folder to salusfx (for example) and use notepad++ to find&replace in files "salusfy" to "salusfx" and then upload it to HA. In config use platform: salusfx

**Comment by floringhimie** [comment]
My last comment should be a possible solution.

**Comment by cpass-watch** [comment]
Yes that worked thank you, I now have two Salus temp controllers
