### ISSUE TITLE
Deprecated constants which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by GigiPompieru** [floringhimie/salusfy#15]
Hello, the HA logs show the following message:

``
CURRENT_HVAC_HEAT was used from salusfy3, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please create a bug report at https://github.com/floringhimie/salusfy/issues
CURRENT_HVAC_IDLE was used from salusfy3, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please create a bug report at https://github.com/floringhimie/salusfy/issues
HVAC_MODE_HEAT was used from salusfy3, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/floringhimie/salusfy/issues
HVAC_MODE_OFF was used from salusfy3, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/floringhimie/salusfy/issues
SUPPORT_TARGET_TEMPERATURE was used from salusfy3, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/floringhimie/salusfy/issues
``

Can you please update the component?

**Comment by floringhimie** [comment]
done

**Comment by Claudio1L** [comment]
thank you

**Comment by GigiPompieru** [comment]
this broke the thermostat, at least for me. did anyone test it working?

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:360
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:21:17 (1 occurrences)
Last logged: 16:21:17
Error while setting up salusfy platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/salusfy/climate.py", line 78, in async_setup_platform
    await async_setup_reload_service(hass, DOMAIN, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'async_setup_reload_service' is not defined
```
