### ISSUE TITLE
How to expose only temperature.

### ISSUE THREAD

**Issue by Claudio1L** [floringhimie/salusfy#3]
HI, thank you very much for your effort.

Is there a way to expose single entities like current temp or wanted temp?

Thank you again

**Comment by kanteruk** [comment]
Hi, it work for me:
sensor:
  - platform: template
    sensors:
      salus_temperature:
        friendly_name: "Salus Current Temperature"
        value_template: "{{ state_attr('climate.salus_thermostat', 'current_temperature') }}"
        unit_of_measurement: '°C'
        device_class: temperature

**Comment by Claudio1L** [comment]
Thank you.

Using the same config, at the verification I got:

Invalid config for [sensor.template]: expected dictionary for dictionary value @ data['sensors']. Got None
extra keys not allowed @ data['device_class']. Got 'temperature'
extra keys not allowed @ data['friendly_name']. Got 'Salus Current Temperature'
extra keys not allowed @ data['salus_temperature']. Got None
extra keys not allowed @ data['unit_of_measurement']. Got '°C'
extra keys not allowed @ data['value_template']. Got "{{ state_attr('climate.salus_thermostat', 'current_temperature') }}". (See ?, line ?).

Am I missing something? Syntax?

**Comment by floringhimie** [comment]
I think you have an indentation issue, check here [Link](https://community.home-assistant.io/t/sensor-template-problem-expected-a-dictionary-for-dictionary-value/144218)

**Comment by Claudio1L** [comment]
Thank you very much!

Worked with:
  - platform: template
    sensors:
      salus_temperature:
        friendly_name: "Salus Current Temperature"
        value_template: "{{ state_attr('climate.salus_thermostat', 'current_temperature') }}"
        unit_of_measurement: '°C'
        device_class: temperature

Thanks a lot again
